
service:
  type: LoadBalancer
  port: 80
image:
  pullPolicy: Always
ingress:
  path: /
  hosts:
    - chart-example.local
tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "application"
  effect: "NoSchedule"
