apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-python-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: application
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-python-app
    helm:
      valueFiles:
        - values-production.yaml
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
